import React, { PureComponent } from 'react'
import { FormattedMessage } from 'react-intl'

class SolutionSection extends PureComponent {
  render() {
    return (
      <section id=" challenge" className="switchable bg--secondary height-auto">
        <div className="container pos-vertical-center">
          <div className="row text-center">
            <h2 style={{ marginBottom: '5px' }}>
              <FormattedMessage id="solution_title" />
            </h2>
            <p
              className="type--uppercase type--bold"
              style={{ marginBottom: '10px' }}
            >
              <FormattedMessage id="solution_subtitle" />
            </p>
          </div>
          <div className="row">
            <div className="col-md-4">
              <div className="switchable__text">
                <p>
                  Using <strong>a smart contract based marketplace</strong> on
                  the Ethereum network, it becomes possible to unlock this
                  value. Via their gateway operator, the sensor owners place the
                  data generated by their sensors up for sale (while staking
                  some of their DTX tokens), and buyers can discover and
                  purchase access to the data using that same DTX token.{' '}
                </p>
                <p>
                  The gateway operator will run{' '}
                  <strong>their own Ethereum mainnet blockchain node</strong>{' '}
                  and run <strong>the open-source DataBrokerDAO dAPI</strong>{' '}
                  (distributed API) on top. Data generated by the sensors of
                  their clients is sent (within the same datacenter) to their
                  dAPI which check who has purchased access and{' '}
                  <strong>
                    send the data directly on to the location specified by the
                    buyer
                  </strong>{' '}
                  on purchasing.
                </p>
              </div>
            </div>
            <div className="col-md-8">
              <img
                src="/img/DATABROKER_INFOGRAPHIC_07-02.png"
                className="app-translate-5"
                style={{ marginTop: '20px' }}
                alt="The challenge"
              />
            </div>
          </div>
          <div className="row">
            <div className="col-md-8">
              <img
                src="/img/DATABROKER_INFOGRAPHIC_07-03.png"
                className="app-translate-5"
                style={{ marginTop: '20px' }}
                alt="The challenge"
              />
            </div>
            <div className="col-md-4">
              <div className="switchable__text">
                <p>
                  Since the{' '}
                  <strong>
                    gateway operator is already set up to deal with the data its
                    clients generate
                  </strong>, routing purchased data streams to a location on the
                  internet is a straightforward extension.
                </p>
                <p>
                  For doing so, the gateway operator is awarded{' '}
                  <strong>10% of each transaction in DTX tokens</strong>. The{' '}
                  <strong>platform also earns 10%</strong> and, most
                  importantly,{' '}
                  <strong>
                    the lion share goes to the sensor owner receiving 80%
                  </strong>{' '}
                  of the proceeds.
                </p>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-4">
              <div className="switchable__text">
                <p>
                  To move from a local to a global marketplace, the{' '}
                  <strong>
                    DataBroker DAO implementation is replicated with a multitude
                    of gateway operators around the world
                  </strong>.
                </p>
                <p>
                  This grants access to a global market for data.{' '}
                  <strong>
                    Anyone in the world will be able to buy any available data
                    anywhere
                  </strong>, making it truly,{' '}
                  <strong>“a global market for local data”</strong>.
                </p>
              </div>
            </div>
            <div className="col-md-8">
              <img
                src="/img/DATABROKER_INFOGRAPHIC_07-04.png"
                className="app-translate-5"
                style={{ marginTop: '20px' }}
                alt="The challenge"
              />
            </div>
          </div>
        </div>
      </section>
    )
  }
}

export default SolutionSection
